#!/usr/bin/env bash
# Works out the next release, writes it into app.json, and adds its CHANGELOG section. Everything
# `prepare-release.yml` does to the tree, in one script you can run locally to see the diff it
# would open a PR with:
#
#   bash .github/scripts/prepare-release.sh patch && git diff
#
# WHAT IT SETS, and why both. `expo.version` is the release's identity: release.yml refuses to cut a
# tag that disagrees with it, and every rolling build afterwards counts from it (`<base>.<N>` — see
# compute-build-version.sh). `expo.android.versionCode` is what Android orders installs by, and
# release.yml separately refuses a release whose code didn't move past the previous tag's. Two
# fields, two guards, and the guards fail ~20 minutes into a macOS build — which is the whole reason
# this exists rather than being a note in the docs telling you to edit both by hand.
#
# Deliberately does NOT create the tag. The tag is release.yml's to make, at the end of a run that
# produced the binaries, so a tag never exists without them.
#
# Usage: prepare-release.sh <patch|minor|major>
#   Writes `version`, `tag` and `previous_tag` to $GITHUB_OUTPUT when running in Actions.
set -euo pipefail

BUMP="${1:?usage: prepare-release.sh <patch|minor|major>}"
APP_JSON="apps/mobile/app.json"
CHANGELOG="CHANGELOG.md"

CURRENT="$(jq -r '.expo.version' "$APP_JSON")"
CODE="$(jq -r '.expo.android.versionCode // 1' "$APP_JSON")"

# Reject anything that isn't three plain integers before doing arithmetic on it — a pre-release
# suffix would parse into garbage here, and `compareVersions` in the app can't order one either.
if ! [[ "$CURRENT" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "::error::$APP_JSON has version '$CURRENT', which isn't X.Y.Z. Fix it by hand first."
  exit 1
fi

IFS=. read -r MAJOR MINOR PATCH <<<"$CURRENT"
case "$BUMP" in
  major) MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0 ;;
  minor) MINOR=$((MINOR + 1)); PATCH=0 ;;
  patch) PATCH=$((PATCH + 1)) ;;
  *) echo "::error::unknown bump '$BUMP' (expected patch, minor or major)"; exit 1 ;;
esac

NEXT="${MAJOR}.${MINOR}.${PATCH}"
NEXT_CODE=$((CODE + 1))
TAG="v${NEXT}"

if git rev-parse -q --verify "refs/tags/${TAG}" >/dev/null; then
  echo "::error::${TAG} already exists. ${CURRENT} -> ${NEXT} would re-cut a shipped release."
  exit 1
fi

# Newest existing release tag, for the changelog range. Empty on the very first release.
PREV_TAG="$(git tag -l 'v*' --sort=-v:refname | head -n1)"

echo "${CURRENT} -> ${NEXT} (versionCode ${CODE} -> ${NEXT_CODE}), changelog from ${PREV_TAG:-the beginning}."

tmp="$(mktemp)"
jq --arg v "$NEXT" --argjson c "$NEXT_CODE" \
  '.expo.version = $v | .expo.android.versionCode = $c' "$APP_JSON" > "$tmp"
mv "$tmp" "$APP_JSON"

# ── CHANGELOG ─────────────────────────────────────────────────────────────────────────────────────
# Merge commits are dropped: this repo merges PRs rather than squashing them, so keeping them would
# list every change twice — once as "Merge pull request #118 from claude/…" and once as the actual
# subject. The subjects are the useful half.
#
# `release: X.Y.Z` commits are dropped too, and the one that gets caught is always the PREVIOUS
# release's: this runs before its own bump is committed, so the range starts at the last tag and
# picks up the bump that immediately followed it. "The previous release happened" is not a change
# in this one.
RANGE="HEAD"
[ -n "$PREV_TAG" ] && RANGE="${PREV_TAG}..HEAD"
ENTRIES="$(git log --no-merges --invert-grep --grep='^release: [0-9]' --format='- %s (%h)' "$RANGE")"
[ -n "$ENTRIES" ] || ENTRIES="- No changes recorded."

[ -f "$CHANGELOG" ] || printf '# Changelog\n\nEvery released version, newest first. Generated by `.github/scripts/prepare-release.sh`.\n' > "$CHANGELOG"

# Trailing blank line, not a leading one: this block is spliced in immediately ABOVE an existing
# `## ` heading, and the header above it already ends with a blank. Leading it would double that
# blank and leave the new section jammed against the one it displaced.
section="$(mktemp)"
{
  printf '## %s — %s\n\n' "$NEXT" "$(date -u +%Y-%m-%d)"
  printf '%s\n\n' "$ENTRIES"
} > "$section"

# Splice the new section in directly after the file's header block (everything before the first
# `## ` heading), so the list stays newest-first without rewriting the entries already there.
awk -v section="$section" '
  !done && /^## / { while ((getline line < section) > 0) print line; done = 1 }
  { print }
  END { if (!done) { while ((getline line < section) > 0) print line } }
' "$CHANGELOG" > "$section.out"
mv "$section.out" "$CHANGELOG"

if [ -n "${GITHUB_OUTPUT:-}" ]; then
  {
    echo "version=${NEXT}"
    echo "tag=${TAG}"
    echo "previous_tag=${PREV_TAG}"
  } >> "$GITHUB_OUTPUT"
fi
