/**
 * The mock catalog's art, served out of this repo over jsDelivr — see `assets/mock/README.md` for
 * what the files are and where the comic pages come from.
 *
 * Serving beats bundling on the one axis that isn't taste: a bundled page resolves to a resource
 * path in a release build, and the download engine's `PageFetcher` (`downloads/fetch-page.ts`)
 * handles `data:` URIs and http(s) URLs only. Bundling made downloading a mock chapter
 * unrunnable; a URL is the shape every real source already hands it. Keeping ~1.7MB of fixtures
 * out of builds that can't reach them is the bonus, not the reason.
 *
 * `REF` is a commit rather than a branch so that a branch which redraws the art renders its OWN
 * set: `@main` would 404 for every file until the branch merged, and a 404 is not just a missing
 * screenshot — the `downloads.yaml` flows assert a real page fetch completes. Redrawing the art
 * means bumping this to the commit that carries it. That commit stays fetchable even if its branch
 * is squash-merged and deleted, because GitHub keeps `refs/pull/N/head` forever.
 */
const REF = 'd0801365f22dd7ede023cd2a5c643024b1b18199';
const ASSETS = `https://cdn.jsdelivr.net/gh/porksphere/comical-app@${REF}/apps/mobile/assets/mock`;

const set = (dir: string, count: number, ext: string): string[] =>
  Array.from({ length: count }, (_, i) => `${ASSETS}/${dir}/${String(i).padStart(2, '0')}.${ext}`);

/** Generated by `scripts/generate-mock-covers.py`. */
export const MOCK_COVERS: string[] = set('covers', 24, 'png');

/** Covers for the one bridge whose thumbnails AREN'T a uniform 2:3, so `SeriesCard`'s shrink
 *  animation has something to fire on (see `VARIED_ASPECT_BRIDGE` in `mock.ts`). The sizes are
 *  drawn by `scripts/generate-mock-covers.py`. */
export const MOCK_COVERS_VARIED: string[] = set('covers-varied', 5, 'png');

/** Bridge list icons. */
export const MOCK_THUMBS: string[] = set('thumbs', 6, 'png');

/** Pepper&Carrot by David Revoy, CC BY 4.0. The licence requires attribution — it is carried in
 *  `assets/mock/README.md`, which is also where the note on why this isn't public-domain 1907
 *  newspaper art lives. */
export const MOCK_PAGES: string[] = set('pages', 6, 'jpg');
