/**
 * The mock catalog's art, served out of this repo over jsDelivr — see `assets/mock/README.md` for
 * what the files are and where the comic pages come from.
 *
 * Serving beats bundling on the one axis that isn't taste: a bundled page resolves to a resource
 * path in a release build, and the download engine's `PageFetcher` (`downloads/fetch-page.ts`)
 * handles `data:` URIs and http(s) URLs only. Bundling made downloading a mock chapter
 * unrunnable; a URL is the shape every real source already hands it. Keeping ~1.7MB of fixtures
 * out of builds that can't reach them is the bonus, not the reason.
 *
 * `REF` follows `main` by default, and CI overrides it with the commit under test. That split is
 * what removes the manual step this used to carry: pinning a commit here meant every change to
 * `assets/mock/` also had to bump this line, and forgetting left the app serving the previous art
 * with nothing failing — a screenshot run shot the wrong covers exactly that way. `main` needs no
 * bump; the override is what keeps a branch's OWN art in its own screenshots and e2e runs, which a
 * bare `main` could not do.
 *
 * Consequence worth knowing: a branch that adds art shows `main`'s set anywhere the override isn't
 * set (local dev), until it merges.
 */
const REF = process.env.EXPO_PUBLIC_COMICAL_MOCK_REF || 'main';
const ASSETS = `https://cdn.jsdelivr.net/gh/porksphere/comical-app@${REF}/apps/mobile/assets/mock`;

const set = (dir: string, count: number, ext: string): string[] =>
  Array.from({ length: count }, (_, i) => `${ASSETS}/${dir}/${String(i).padStart(2, '0')}.${ext}`);

/** Generated by `scripts/generate-mock-covers.py`. */
export const MOCK_COVERS: string[] = set('covers', 24, 'png');

/** Covers for the one bridge whose thumbnails AREN'T a uniform 2:3, so `SeriesCard`'s shrink
 *  animation has something to fire on (see `VARIED_ASPECT_BRIDGE` in `mock.ts`). The sizes are
 *  drawn by `scripts/generate-mock-covers.py`. */
export const MOCK_COVERS_VARIED: string[] = set('covers-varied', 5, 'png');

/** Bridge list icons. */
export const MOCK_THUMBS: string[] = set('thumbs', 6, 'png');

/** Pepper&Carrot by David Revoy, CC BY 4.0. The licence requires attribution — it is carried in
 *  `assets/mock/README.md`, which is also where the note on why this isn't public-domain 1907
 *  newspaper art lives. */
export const MOCK_PAGES: string[] = set('pages', 6, 'jpg');
