/**
 * The mock catalog's bundled art — see `assets/mock/README.md` for what these are and where the
 * comic pages come from.
 *
 * `require` calls have to be literal for Metro to resolve them, so the sets are spelled out rather
 * than built in a loop. `resolveAssetSource` turns each into a URI string because that is what the
 * rest of the data layer passes around (`thumbnailUrl`, `Page.url`, …) — handing components a
 * module number instead would mean widening those types everywhere for the benefit of fixtures.
 */
import { Image } from 'react-native';

const uri = (mod: number): string => Image.resolveAssetSource(mod).uri;

/** Generated by `scripts/generate-mock-covers.py`. */
export const MOCK_COVERS: string[] = [
  require('../../assets/mock/covers/00.png'),
  require('../../assets/mock/covers/01.png'),
  require('../../assets/mock/covers/02.png'),
  require('../../assets/mock/covers/03.png'),
  require('../../assets/mock/covers/04.png'),
  require('../../assets/mock/covers/05.png'),
  require('../../assets/mock/covers/06.png'),
  require('../../assets/mock/covers/07.png'),
  require('../../assets/mock/covers/08.png'),
  require('../../assets/mock/covers/09.png'),
  require('../../assets/mock/covers/10.png'),
  require('../../assets/mock/covers/11.png'),
  require('../../assets/mock/covers/12.png'),
  require('../../assets/mock/covers/13.png'),
  require('../../assets/mock/covers/14.png'),
  require('../../assets/mock/covers/15.png'),
  require('../../assets/mock/covers/16.png'),
  require('../../assets/mock/covers/17.png'),
  require('../../assets/mock/covers/18.png'),
  require('../../assets/mock/covers/19.png'),
  require('../../assets/mock/covers/20.png'),
  require('../../assets/mock/covers/21.png'),
  require('../../assets/mock/covers/22.png'),
  require('../../assets/mock/covers/23.png'),
].map(uri);

/** Covers for the one bridge whose thumbnails AREN'T a uniform 2:3, so `SeriesCard`'s shrink
 *  animation has something to fire on (see `VARIED_ASPECT_BRIDGE` in `mock.ts`). The sizes are
 *  drawn by `scripts/generate-mock-covers.py`. */
export const MOCK_COVERS_VARIED: string[] = [
  require('../../assets/mock/covers-varied/00.png'),
  require('../../assets/mock/covers-varied/01.png'),
  require('../../assets/mock/covers-varied/02.png'),
  require('../../assets/mock/covers-varied/03.png'),
  require('../../assets/mock/covers-varied/04.png'),
].map(uri);

/** Bridge list icons. */
export const MOCK_THUMBS: string[] = [
  require('../../assets/mock/thumbs/00.png'),
  require('../../assets/mock/thumbs/01.png'),
  require('../../assets/mock/thumbs/02.png'),
  require('../../assets/mock/thumbs/03.png'),
  require('../../assets/mock/thumbs/04.png'),
  require('../../assets/mock/thumbs/05.png'),
].map(uri);

/** Little Nemo in Slumberland, Winsor McCay, 1907. Public domain. */
export const MOCK_PAGES: string[] = [
  require('../../assets/mock/pages/00.jpg'),
  require('../../assets/mock/pages/01.jpg'),
  require('../../assets/mock/pages/02.jpg'),
  require('../../assets/mock/pages/03.jpg'),
  require('../../assets/mock/pages/04.jpg'),
  require('../../assets/mock/pages/05.jpg'),
].map(uri);
